/**
 * Healthcare category and token icon catalog data (Italian clinical vocabulary).
 */
import { CATEGORY_COLOR } from './categoryIconColors';

export interface CategoryIconSpec {
  iconKey: string;
  iconColor: string;
}

function spec(iconKey: string, iconColor: string): CategoryIconSpec {
  return { iconKey, iconColor };
}

/** Category container names → icon (exact normalized match). */
export const HEALTHCARE_EXACT_CATEGORY_ICONS: Record<string, CategoryIconSpec> = {
  // Visite
  'tipo visita': spec('ClipboardList', CATEGORY_COLOR.visitType),
  'tipologia visita': spec('ClipboardList', CATEGORY_COLOR.visitType),
  'tipi di visita': spec('ClipboardList', CATEGORY_COLOR.visitType),
  'modalita visita': spec('ClipboardList', CATEGORY_COLOR.visitType),
  'modalità visita': spec('ClipboardList', CATEGORY_COLOR.visitType),
  'visita': spec('Stethoscope', CATEGORY_COLOR.visit),
  'visite': spec('Stethoscope', CATEGORY_COLOR.visit),

  // Esami
  'esame': spec('FlaskConical', CATEGORY_COLOR.exam),
  'esami': spec('FlaskConical', CATEGORY_COLOR.exam),
  'esame strumentale': spec('Activity', CATEGORY_COLOR.exam),
  'esami strumentali': spec('Activity', CATEGORY_COLOR.exam),
  'diagnostica': spec('Scan', CATEGORY_COLOR.imaging),
  'diagnostica per immagini': spec('Scan', CATEGORY_COLOR.imaging),
  'imaging': spec('Scan', CATEGORY_COLOR.imaging),
  'laboratorio': spec('Droplet', CATEGORY_COLOR.lab),
  'analisi': spec('TestTube2', CATEGORY_COLOR.lab),

  // Organi / anatomia / parti del corpo
  'organo': spec('Heart', CATEGORY_COLOR.organ),
  'organi': spec('Heart', CATEGORY_COLOR.organ),
  'anatomia': spec('Layers', CATEGORY_COLOR.anatomy),
  'apparato': spec('Layers', CATEGORY_COLOR.anatomy),
  'distretto anatomico': spec('Layers', CATEGORY_COLOR.anatomy),
  'distretto': spec('Layers', CATEGORY_COLOR.anatomy),
  'parte del corpo': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'parti del corpo': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'parte corporea': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'parti corporee': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'segmento corporeo': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'segmenti corporei': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'regione corporea': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'regioni corporee': spec('PersonStanding', CATEGORY_COLOR.bodyPart),

  // Posizione / lateralità
  'posizione': spec('ArrowLeftRight', CATEGORY_COLOR.position),
  'posizioni': spec('ArrowLeftRight', CATEGORY_COLOR.position),
  'lato': spec('ArrowLeftRight', CATEGORY_COLOR.position),
  'lateralita': spec('ArrowLeftRight', CATEGORY_COLOR.position),
  'lateralità': spec('ArrowLeftRight', CATEGORY_COLOR.position),
  'sede anatomica': spec('CircleDot', CATEGORY_COLOR.position),
  'estensione': spec('Maximize2', CATEGORY_COLOR.position),

  // Specialità e altro (sanità)
  'specialita': spec('Puzzle', CATEGORY_COLOR.specialty),
  'specialità': spec('Puzzle', CATEGORY_COLOR.specialty),
  'specialita medica': spec('Puzzle', CATEGORY_COLOR.specialty),
  'specialità medica': spec('Puzzle', CATEGORY_COLOR.specialty),
  'branca': spec('Puzzle', CATEGORY_COLOR.specialty),
  'fascia di eta': spec('AgeGrowth', CATEGORY_COLOR.age),
  'fascia di età': spec('AgeGrowth', CATEGORY_COLOR.age),
  'fasce di eta': spec('AgeGrowth', CATEGORY_COLOR.age),
  'fasce di età': spec('AgeGrowth', CATEGORY_COLOR.age),
  'fascia eta': spec('AgeGrowth', CATEGORY_COLOR.age),
  'fascia età': spec('AgeGrowth', CATEGORY_COLOR.age),
  'diagnosi': spec('FileText', CATEGORY_COLOR.diagnosis),
  'sintomo': spec('Thermometer', CATEGORY_COLOR.symptom),
  'sintomi': spec('Thermometer', CATEGORY_COLOR.symptom),
  'farmaco': spec('Pill', CATEGORY_COLOR.drug),
  'farmaci': spec('Pill', CATEGORY_COLOR.drug),
  'terapia': spec('Pill', CATEGORY_COLOR.drug),
  'prestazione': spec('ClipboardCheck', CATEGORY_COLOR.service),
  'prestazioni': spec('ClipboardCheck', CATEGORY_COLOR.service),
  'sede': spec('MapPin', CATEGORY_COLOR.location),
  'struttura': spec('Building2', CATEGORY_COLOR.location),
  'priorita': spec('AlertTriangle', CATEGORY_COLOR.urgency),
  'priorità': spec('AlertTriangle', CATEGORY_COLOR.urgency),
  'urgenza': spec('AlertTriangle', CATEGORY_COLOR.urgency),
  'sesso': spec('UserRound', CATEGORY_COLOR.gender),
  'genere': spec('UserRound', CATEGORY_COLOR.gender),
  'medico': spec('User', CATEGORY_COLOR.staff),
  'operatore': spec('User', CATEGORY_COLOR.staff),
  'vaccino': spec('Syringe', CATEGORY_COLOR.procedure),
  'vaccinazione': spec('Syringe', CATEGORY_COLOR.procedure),
  'ricovero': spec('Building2', CATEGORY_COLOR.service),
  'day hospital': spec('CalendarCheck', CATEGORY_COLOR.visitType),
};

/** Category name keyword rules (longer phrases first). */
export const HEALTHCARE_CATEGORY_KEYWORD_RULES: Array<{ keywords: string[]; spec: CategoryIconSpec }> = [
  { keywords: ['diagnostica per immagini', 'imaging'], spec: spec('Scan', CATEGORY_COLOR.imaging) },
  { keywords: ['tipo visita', 'tipologia visita', 'modalita visita', 'modalità visita'], spec: spec('ClipboardList', CATEGORY_COLOR.visitType) },
  {
    keywords: [
      'parte del corpo',
      'parti del corpo',
      'parte corporea',
      'segmento corporeo',
      'regione corporea',
      'arto',
      'articolazione',
    ],
    spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  },
  { keywords: ['organo', 'organi'], spec: spec('Heart', CATEGORY_COLOR.organ) },
  { keywords: ['anatomia', 'apparato', 'distretto anatomico'], spec: spec('Layers', CATEGORY_COLOR.anatomy) },
  { keywords: ['posizione', 'lateralita', 'lateralità', 'lato', 'estensione'], spec: spec('ArrowLeftRight', CATEGORY_COLOR.position) },
  { keywords: ['prima visita', 'nuova visita', 'ingresso'], spec: spec('CalendarPlus', CATEGORY_COLOR.visitType) },
  { keywords: ['controllo', 'follow up', 'follow-up', 'rivalutazione', 'richiamo'], spec: spec('RefreshCw', CATEGORY_COLOR.visitType) },
  { keywords: ['teleconsulto', 'televisita', 'videochiamata'], spec: spec('Video', CATEGORY_COLOR.visitType) },
  { keywords: ['telefon'], spec: spec('Phone', CATEGORY_COLOR.visitType) },
  { keywords: ['cardiolog'], spec: spec('HeartPulse', CATEGORY_COLOR.specialty) },
  { keywords: ['neurolog', 'encefal'], spec: spec('Brain', CATEGORY_COLOR.specialty) },
  { keywords: ['ortoped', 'traumatolog'], spec: spec('Bone', CATEGORY_COLOR.specialty) },
  { keywords: ['pediatr', 'neonat', 'bambin'], spec: spec('Baby', CATEGORY_COLOR.age) },
  { keywords: ['oculist', 'oftalmolog'], spec: spec('Eye', CATEGORY_COLOR.specialty) },
  { keywords: ['otorin', 'orecchio', 'udito'], spec: spec('Ear', CATEGORY_COLOR.specialty) },
  { keywords: ['pneumolog', 'polmon'], spec: spec('Wind', CATEGORY_COLOR.specialty) },
  { keywords: ['psicolog', 'psichiatr'], spec: spec('MessageCircle', CATEGORY_COLOR.mental) },
  { keywords: ['radiolog', 'radiograf'], spec: spec('Scan', CATEGORY_COLOR.imaging) },
  { keywords: ['ecograf', 'ultrasuon'], spec: spec('Waves', CATEGORY_COLOR.imaging) },
  { keywords: ['laborator', 'emocrom', 'sangue'], spec: spec('Droplet', CATEGORY_COLOR.lab) },
  { keywords: ['urin', 'urina'], spec: spec('TestTube2', CATEGORY_COLOR.lab) },
  { keywords: ['visita', 'ambulator'], spec: spec('Stethoscope', CATEGORY_COLOR.visit) },
  { keywords: ['esame', 'esami', 'strumentale'], spec: spec('FlaskConical', CATEGORY_COLOR.exam) },
  { keywords: ['fasce di eta', 'fasce di età', 'fascia di eta', 'fascia di età', 'fascia eta'], spec: spec('AgeGrowth', CATEGORY_COLOR.age) },
  { keywords: ['fascia', 'eta', 'età', 'anni'], spec: spec('AgeGrowth', CATEGORY_COLOR.age) },
  { keywords: ['special', 'branca'], spec: spec('Puzzle', CATEGORY_COLOR.specialty) },
  { keywords: ['visite'], spec: spec('Stethoscope', CATEGORY_COLOR.visit) },
  { keywords: ['sintom', 'dolore', 'febbre'], spec: spec('Thermometer', CATEGORY_COLOR.symptom) },
  { keywords: ['farmaco', 'terapia'], spec: spec('Pill', CATEGORY_COLOR.drug) },
  { keywords: ['prestaz', 'servizio'], spec: spec('ClipboardCheck', CATEGORY_COLOR.service) },
  { keywords: ['urgen', 'emergenz'], spec: spec('AlertTriangle', CATEGORY_COLOR.urgency) },
  { keywords: ['oncolog', 'tumor'], spec: spec('Radiation', CATEGORY_COLOR.imaging) },
  { keywords: ['dermatolog', 'pelle'], spec: spec('ScanSearch', CATEGORY_COLOR.specialty) },
  { keywords: ['endoscop', 'colonscop', 'gastroscop'], spec: spec('SearchCheck', CATEGORY_COLOR.exam) },
];

/**
 * Exact token phrase → icon (normalized). Checked before keyword rules.
 */
export const HEALTHCARE_EXACT_TOKEN_ICONS: Record<string, CategoryIconSpec> = {
  'prima visita': spec('CalendarPlus', CATEGORY_COLOR.visitType),
  'visita di controllo': spec('RefreshCw', CATEGORY_COLOR.visitType),
  'visita controllo': spec('RefreshCw', CATEGORY_COLOR.visitType),
  'visita urgente': spec('AlertTriangle', CATEGORY_COLOR.urgency),
  'seconda opinione': spec('MessageCircle', CATEGORY_COLOR.visitType),
  'ecocardiogramma': spec('HeartPulse', CATEGORY_COLOR.exam),
  'ecocardiografia': spec('HeartPulse', CATEGORY_COLOR.exam),
  'elettrocardiogramma': spec('Activity', CATEGORY_COLOR.exam),
  'ecg': spec('Activity', CATEGORY_COLOR.exam),
  'holter': spec('Activity', CATEGORY_COLOR.exam),
  'holter cardiaco': spec('Activity', CATEGORY_COLOR.exam),
  'test da sforzo': spec('Activity', CATEGORY_COLOR.exam),
  'ergometria': spec('Activity', CATEGORY_COLOR.exam),
  'spirometria': spec('Wind', CATEGORY_COLOR.exam),
  'elettroencefalogramma': spec('Brain', CATEGORY_COLOR.exam),
  'eeg': spec('Brain', CATEGORY_COLOR.exam),
  'emocromo': spec('Droplet', CATEGORY_COLOR.lab),
  'emocromo completo': spec('Droplet', CATEGORY_COLOR.lab),
  'glicemia': spec('Droplet', CATEGORY_COLOR.lab),
  'colesterolo': spec('Droplet', CATEGORY_COLOR.lab),
  'esame urine': spec('TestTube2', CATEGORY_COLOR.lab),
  'urinocoltura': spec('TestTube2', CATEGORY_COLOR.lab),
  'mammografia': spec('Scan', CATEGORY_COLOR.imaging),
  'risonanza magnetica': spec('Scan', CATEGORY_COLOR.imaging),
  'rmn': spec('Scan', CATEGORY_COLOR.imaging),
  'tac': spec('Scan', CATEGORY_COLOR.imaging),
  'tomografia': spec('Scan', CATEGORY_COLOR.imaging),
  'rx torace': spec('Scan', CATEGORY_COLOR.imaging),
  'radiografia': spec('Scan', CATEGORY_COLOR.imaging),
  'ecografia': spec('Waves', CATEGORY_COLOR.imaging),
  'ecografia addominale': spec('Waves', CATEGORY_COLOR.imaging),
  'pet': spec('Radiation', CATEGORY_COLOR.imaging),
  'scintigrafia': spec('Radiation', CATEGORY_COLOR.imaging),
  'densitometria': spec('Bone', CATEGORY_COLOR.imaging),
  'colonscopia': spec('SearchCheck', CATEGORY_COLOR.exam),
  'gastroscopia': spec('SearchCheck', CATEGORY_COLOR.exam),
  'endoscopia': spec('SearchCheck', CATEGORY_COLOR.exam),
  'biopsia': spec('Syringe', CATEGORY_COLOR.exam),
  'audiometria': spec('Ear', CATEGORY_COLOR.exam),
  'campimetria': spec('Eye', CATEGORY_COLOR.exam),
  'cuore': spec('Heart', CATEGORY_COLOR.organ),
  'aorta': spec('HeartPulse', CATEGORY_COLOR.organ),
  'arterie': spec('HeartPulse', CATEGORY_COLOR.organ),
  'vene': spec('HeartPulse', CATEGORY_COLOR.organ),
  'fegato': spec('Layers', CATEGORY_COLOR.organ),
  'rene': spec('Droplet', CATEGORY_COLOR.organ),
  'reni': spec('Droplet', CATEGORY_COLOR.organ),
  'polmone': spec('Wind', CATEGORY_COLOR.organ),
  'polmoni': spec('Wind', CATEGORY_COLOR.organ),
  'cervello': spec('Brain', CATEGORY_COLOR.organ),
  'stomaco': spec('SearchCheck', CATEGORY_COLOR.organ),
  'intestino': spec('Layers', CATEGORY_COLOR.organ),
  'colon': spec('Layers', CATEGORY_COLOR.organ),
  'pancreas': spec('Syringe', CATEGORY_COLOR.organ),
  'tiroide': spec('CircleDot', CATEGORY_COLOR.organ),
  'prostata': spec('CircleDot', CATEGORY_COLOR.organ),
  'utero': spec('CircleDot', CATEGORY_COLOR.organ),
  'ovaio': spec('CircleDot', CATEGORY_COLOR.organ),
  'ossa': spec('Bone', CATEGORY_COLOR.organ),
  'colonna vertebrale': spec('Bone', CATEGORY_COLOR.organ),
  'addome': spec('Scan', CATEGORY_COLOR.anatomy),
  'addominale': spec('Scan', CATEGORY_COLOR.anatomy),
  'torace': spec('Scan', CATEGORY_COLOR.anatomy),
  'toracico': spec('Scan', CATEGORY_COLOR.anatomy),
  'bacino': spec('CircleDot', CATEGORY_COLOR.anatomy),
  'pelvico': spec('CircleDot', CATEGORY_COLOR.anatomy),
  'sinistra': spec('ArrowLeft', CATEGORY_COLOR.position),
  'sinistro': spec('ArrowLeft', CATEGORY_COLOR.position),
  'destra': spec('ArrowRight', CATEGORY_COLOR.position),
  'destro': spec('ArrowRight', CATEGORY_COLOR.position),
  'bilaterale': spec('ArrowLeftRight', CATEGORY_COLOR.position),
  'superiore': spec('ArrowUp', CATEGORY_COLOR.position),
  'inferiore': spec('ArrowDown', CATEGORY_COLOR.position),
  'alto': spec('ArrowUp', CATEGORY_COLOR.position),
  'basso': spec('ArrowDown', CATEGORY_COLOR.position),
  'anteriore': spec('ArrowUp', CATEGORY_COLOR.position),
  'posteriore': spec('ArrowDown', CATEGORY_COLOR.position),
  'mediale': spec('CircleDot', CATEGORY_COLOR.position),
  'centrale': spec('CircleDot', CATEGORY_COLOR.position),
  'completo': spec('Maximize2', CATEGORY_COLOR.position),
  'totale': spec('Maximize2', CATEGORY_COLOR.position),
  'parziale': spec('Layers', CATEGORY_COLOR.position),
  'monolaterale': spec('ArrowRight', CATEGORY_COLOR.position),

  // Parti del corpo (arti e segmenti)
  'testa': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'cranio': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'faccia': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'viso': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'collo': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'petto': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'schiena': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'spalla': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'spalle': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'braccio': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'braccia': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'avambraccio': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'gomito': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'polso': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'mano': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'mani': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'dita': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'anca': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'anche': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'gamba': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'gambe': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'coscia': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'cosce': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'ginocchio': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'ginocchia': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'caviglia': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'piede': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'piedi': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'tallone': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'articolazione': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
  'articolazioni': spec('PersonStanding', CATEGORY_COLOR.bodyPart),
};

/** Token phrase keyword rules — longer/more specific keywords first. */
export const HEALTHCARE_TOKEN_KEYWORD_RULES: Array<{ keywords: string[]; spec: CategoryIconSpec }> = [
  // Visite
  { keywords: ['visita di controllo', 'visita controllo', 'controllo periodico'], spec: spec('RefreshCw', CATEGORY_COLOR.visitType) },
  { keywords: ['prima visita', 'nuova visita', 'visita iniziale'], spec: spec('CalendarPlus', CATEGORY_COLOR.visitType) },
  { keywords: ['visita urgente', 'accesso urgente'], spec: spec('AlertTriangle', CATEGORY_COLOR.urgency) },
  { keywords: ['televisita', 'teleconsulto'], spec: spec('Video', CATEGORY_COLOR.visitType) },
  { keywords: ['consulenza', 'seconda opinione'], spec: spec('MessageCircle', CATEGORY_COLOR.visitType) },

  // Esami cardiologici / strumentali
  { keywords: ['ecocardiogramma', 'ecocardiograf', 'ecocardio'], spec: spec('HeartPulse', CATEGORY_COLOR.exam) },
  { keywords: ['elettrocardiogramma', 'elettrocardiograf'], spec: spec('Activity', CATEGORY_COLOR.exam) },
  { keywords: ['holter', 'test da sforzo', 'ergometr'], spec: spec('Activity', CATEGORY_COLOR.exam) },
  { keywords: ['ecg'], spec: spec('Activity', CATEGORY_COLOR.exam) },
  { keywords: ['elettroencefalogramma', 'elettroencefalog'], spec: spec('Brain', CATEGORY_COLOR.exam) },
  { keywords: ['eeg'], spec: spec('Brain', CATEGORY_COLOR.exam) },
  { keywords: ['spirometr'], spec: spec('Wind', CATEGORY_COLOR.exam) },

  // Imaging
  { keywords: ['risonanza magnetica', 'risonanza', 'rmn'], spec: spec('Scan', CATEGORY_COLOR.imaging) },
  { keywords: ['tomografia computerizzata', 'tomografia', 'tac'], spec: spec('Scan', CATEGORY_COLOR.imaging) },
  { keywords: ['radiograf', 'rx '], spec: spec('Scan', CATEGORY_COLOR.imaging) },
  { keywords: ['mammograf'], spec: spec('Scan', CATEGORY_COLOR.imaging) },
  { keywords: ['ecograf', 'ultrasuon'], spec: spec('Waves', CATEGORY_COLOR.imaging) },
  { keywords: ['pet ', 'spect', 'scintigraf'], spec: spec('Radiation', CATEGORY_COLOR.imaging) },
  { keywords: ['densitometr'], spec: spec('Bone', CATEGORY_COLOR.imaging) },

  // Endoscopia / biopsie
  { keywords: ['colonscop', 'gastroscop', 'endoscop', 'rettosigmoidoscop'], spec: spec('SearchCheck', CATEGORY_COLOR.exam) },
  { keywords: ['biops', 'citolog'], spec: spec('Syringe', CATEGORY_COLOR.exam) },

  // Laboratorio
  { keywords: ['emocrom'], spec: spec('Droplet', CATEGORY_COLOR.lab) },
  { keywords: ['glicem', 'colesterol', 'triglicerid', 'emoglob', 'creatinin'], spec: spec('Droplet', CATEGORY_COLOR.lab) },
  { keywords: ['urinocoltura', 'esame urine', 'urinari'], spec: spec('TestTube2', CATEGORY_COLOR.lab) },
  { keywords: ['microbiolog', 'coltura'], spec: spec('Microscope', CATEGORY_COLOR.lab) },

  // Parti del corpo
  { keywords: ['testa', 'cranio', 'faccia', 'viso', 'capo'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['collo', 'cervicale'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['petto', 'schiena', 'torace anteriore'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['spall', 'omero'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['bracc', 'avambracc', 'gomit', 'polso'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['mano', 'mani', 'dita', 'pollice'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['anca', 'anche', 'articolazione coxofemorale'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['gamb', 'cosc', 'ginocch', 'cavigl', 'tallone'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['piede', 'piedi', 'plantar'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },
  { keywords: ['articolaz', 'menisco', 'rotula'], spec: spec('PersonStanding', CATEGORY_COLOR.bodyPart) },

  // Organi
  { keywords: ['miocard', 'cuore', 'cardiac'], spec: spec('Heart', CATEGORY_COLOR.organ) },
  { keywords: ['aorta', 'arteri', 'vascolar', 'coronar'], spec: spec('HeartPulse', CATEGORY_COLOR.organ) },
  { keywords: ['fegat', 'epatic', 'epat'], spec: spec('Layers', CATEGORY_COLOR.organ) },
  { keywords: ['ren', 'renale', 'nefrolog'], spec: spec('Droplet', CATEGORY_COLOR.organ) },
  { keywords: ['polmon', 'bronc', 'pleur'], spec: spec('Wind', CATEGORY_COLOR.organ) },
  { keywords: ['encefal', 'cerebr', 'cervell'], spec: spec('Brain', CATEGORY_COLOR.organ) },
  { keywords: ['gastric', 'stomac', 'duoden', 'intestin', 'colon', 'retto'], spec: spec('Layers', CATEGORY_COLOR.organ) },
  { keywords: ['pancreat'], spec: spec('Syringe', CATEGORY_COLOR.organ) },
  { keywords: ['tiroide', 'tiroidea'], spec: spec('CircleDot', CATEGORY_COLOR.organ) },
  { keywords: ['prostata', 'uter', 'ovar', 'ginecolog'], spec: spec('CircleDot', CATEGORY_COLOR.organ) },
  { keywords: ['vertebr', 'colonna', 'osso', 'scheletr', 'femore', 'tibia'], spec: spec('Bone', CATEGORY_COLOR.organ) },
  { keywords: ['muscol', 'tendin', 'legament'], spec: spec('Bone', CATEGORY_COLOR.organ) },
  { keywords: ['retina', 'cornea', 'ocul'], spec: spec('Eye', CATEGORY_COLOR.organ) },
  { keywords: ['timpano', 'coclea'], spec: spec('Ear', CATEGORY_COLOR.organ) },
  { keywords: ['dermat', 'cutane', 'pelle'], spec: spec('ScanSearch', CATEGORY_COLOR.organ) },

  // Distretti anatomici
  { keywords: ['addomin', 'epigastr', 'mesogastr', 'ipogastr'], spec: spec('Scan', CATEGORY_COLOR.anatomy) },
  { keywords: ['torac', 'mediastin'], spec: spec('Scan', CATEGORY_COLOR.anatomy) },
  { keywords: ['pelv', 'bacin', 'lomb', 'lombare', 'cervical', 'dorsal'], spec: spec('CircleDot', CATEGORY_COLOR.anatomy) },

  // Posizione / lateralità
  { keywords: ['bilaterale', 'bilateral'], spec: spec('ArrowLeftRight', CATEGORY_COLOR.position) },
  { keywords: ['monolaterale', 'unilaterale'], spec: spec('ArrowRight', CATEGORY_COLOR.position) },
  { keywords: ['sinistr', ' sx', 'left'], spec: spec('ArrowLeft', CATEGORY_COLOR.position) },
  { keywords: ['destr', ' dx', 'right'], spec: spec('ArrowRight', CATEGORY_COLOR.position) },
  { keywords: ['superior', 'superiore', 'cranial', 'alto', ' sup'], spec: spec('ArrowUp', CATEGORY_COLOR.position) },
  { keywords: ['inferior', 'caudal', 'basso', ' inf'], spec: spec('ArrowDown', CATEGORY_COLOR.position) },
  { keywords: ['anterior', 'anteriore', 'ventral', 'frontal'], spec: spec('ArrowUp', CATEGORY_COLOR.position) },
  { keywords: ['posterior', 'posteriore', 'dorsal'], spec: spec('ArrowDown', CATEGORY_COLOR.position) },
  { keywords: ['medial', 'mediale', 'centr', 'meso'], spec: spec('CircleDot', CATEGORY_COLOR.position) },
  { keywords: ['completo', 'completa', 'totale', 'intero', 'global'], spec: spec('Maximize2', CATEGORY_COLOR.position) },
  { keywords: ['parziale', 'segmentale', 'local'], spec: spec('Layers', CATEGORY_COLOR.position) },

  // Specialità (token che sono specialità)
  { keywords: ['cardiolog'], spec: spec('HeartPulse', CATEGORY_COLOR.specialty) },
  { keywords: ['neurolog'], spec: spec('Brain', CATEGORY_COLOR.specialty) },
  { keywords: ['ortoped'], spec: spec('Bone', CATEGORY_COLOR.specialty) },
  { keywords: ['pneumolog'], spec: spec('Wind', CATEGORY_COLOR.specialty) },
  { keywords: ['urolog'], spec: spec('Droplet', CATEGORY_COLOR.specialty) },
  { keywords: ['nefrolog'], spec: spec('Droplet', CATEGORY_COLOR.specialty) },
  { keywords: ['gastroenterolog', 'epatolog'], spec: spec('SearchCheck', CATEGORY_COLOR.specialty) },
  { keywords: ['endocrinolog'], spec: spec('CircleDot', CATEGORY_COLOR.specialty) },
  { keywords: ['ematolog'], spec: spec('Droplet', CATEGORY_COLOR.specialty) },
  { keywords: ['oncolog'], spec: spec('Radiation', CATEGORY_COLOR.specialty) },
  { keywords: ['reumatolog'], spec: spec('Bone', CATEGORY_COLOR.specialty) },
  { keywords: ['geriatr'], spec: spec('PersonStanding', CATEGORY_COLOR.specialty) },
  { keywords: ['pediatr'], spec: spec('Baby', CATEGORY_COLOR.specialty) },

  // Sintomi comuni
  { keywords: ['dolore', 'alg', 'febbre', 'dispnea', 'tachicard'], spec: spec('Thermometer', CATEGORY_COLOR.symptom) },
];
